Add preference to display edit/view note button either floating or in top menu
quillpad/quillpad pull request #134
Opened 2023-04-10 17:15 UTC by nofishonfriday

As mentioned in #83, this PR adds a user preference to either show the edit/view note button floating (as FAB, current state) or in the top menu, so users with smaller devices can use this option.
Default is show as FAB, so there's no change in default behaviour.

Demo:
![FAB_option1](https://user-images.githubusercontent.com/7658194/230954482-37068fc0-8578-45b0-b379-8190ee00eb70.gif)

2023-04-10 20:17 UTC, nofishonfriday commented
> It's a cool feature, but I would name the setting "Edit/View note button position" and rename the options to "Floating button" and "Top bar".

Good idea (I wasn't sure about the naming anyway), will do, thanks.
Unless you have some other suggestion @jsixface?

2023-05-04 15:24 UTC, jsixface requested changes
Could you also bring the branch up to date please.

2023-05-06 13:58 UTC, nofishonfriday commented
Updated according to suggestion, changes from your `master` branch are also applied (rebased).

![quillpad pref](https://user-images.githubusercontent.com/7658194/236628437-e4e610a9-80e9-462d-aae4-8aa1d3410a39.jpg)

About the additional commit ('Dynamically set Pin/Unpin menu title (in case the Pin icon isn't visble)':
This is only indirectly related (side effect) to this new Pref (hence I made it a seperate commit), I noticed that on my S4 Mini when showing the Edit/View note button in top bar, the Pin icon moves to the pop up menu (because there isn't enough room to display it), this commit ensures that the Pin/Unpin state is displayed/updated correctly.

![Unpin](https://user-images.githubusercontent.com/7658194/236628662-eb737e67-669e-4697-b817-5ad44b5095bf.png)

2023-05-06 18:40 UTC, jsixface approved these changes

2023-05-06 18:40 UTC, merged

2023-05-06 21:46 UTC, nofishonfriday commented
Thanks for merging.
I've used my own (private) fork with the view/edit button in top bar till now (because on the S4 Mini it's rather unuseable with the FAB), so now I can switch back to your fork again. :)